run:
  tests: true
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - nestif
    - prealloc
    - testpackage
linters-settings:
  lll:
    line-length: 140
  goimports:
    local-prefixes: PLACE_YOUR_PACKAGE_NAME
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - dupl

    - path: "_test.go"
      linters:
        - gocritic
      text: 'hugeParam\: \S+ is heavy \(\d+ bytes\)\; consider passing it by pointer'