version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672

  loki:
    image: grafana/loki:2.4.0
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./configs/loki/loki-config.yaml.prod:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /tmp:/tmp
      - ./configs/promtail/promtail-config.yaml.prod:/etc/promtail/config.yml
    command:
      - --config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - loki

  notify:
    build: .
    container_name: notify
    image: notify
    labels:
      job: notify
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
      - loki
      - promtail
      - grafana

volumes:
  pg-data: