apiVersion: v1
kind: Secret
metadata:
  name: notify-secret
type: Opaque
data:
  {{- $parsedEnv := include "parseDotEnv" . | fromYaml }}
  {{- range $key, $value := $parsedEnv }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}