{{- if .Values.notify.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;' ]
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
      containers:
        - name: notify
          image: {{ .Values.notify.image.repository }}
          envFrom:
            - secretRef:
                name: notify-secret
          ports:
            - containerPort: {{ .Values.notify.service.port }}
{{- end }}