{{- if .Values.notify.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  type: {{ .Values.notify.service.type }}
  selector:
    app: notify
  ports:
    - protocol: TCP
      port: {{ .Values.notify.service.port }}
      targetPort: {{ .Values.notify.service.port }}
{{- end }}