{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storageSize }}
  storageClassName: {{ .Values.rabbitmq.storageClass }}
{{- end }}