{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
{{- end }}