app:
  name: "notification-service"
  version: "v1.0.0"
  countWorkers: 24
  timeout: 5s

grpc:
  port: 8080
  timeout: 5s

storage:
  poolMax: 2
  connAttempts: 10
  connTimeout: 1s

messaging:
  topics:
    - "phone_notify"
    - "mail_notify"
  server:
    rpcExchange: "rpc_server"
    goroutinesCount: 11
    waitTime: 2s
    attempts: 10
    timeout: 2s
  client:
    rpcExchange: "rpc_client"
    waitTime: 2s
    attempts: 10
    timeout: 2s

smtp:
  port: 443

observability:
  trace:
    port: 4317
    retryConfig:
      enabled: true
      initialInterval: 500ms
      maxInterval: 5s
      maxElapsedTime: 1m
  metrics:
    port: 8081

logger:
  logLevel: "dev"
  logPath: "./logs/dev/dev.log"