# Default values for notify.
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Postgres configuration
postgres:
  enabled: true
  image: postgres:13
  storageClass: "standard"
  storageSize: "1Gi"
  service:
    port: 5432
  resources: {}
    # limits:
    #   cpu: "500m"
    #   memory: "512Mi"
    # requests:
    #   cpu: "250m"
  #   memory: "256Mi"

# RabbitMQ configuration
rabbitmq:
  enabled: true
  image: rabbitmq:3.8-management
  storageClass: "standard"
  storageSize: "1Gi"
  service:
    port: 5672
  resources: {}
    # limits:
    #   cpu: "500m"
    #   memory: "512Mi"
    # requests:
    #   cpu: "250m"
  #   memory: "256Mi"

# Notify configuration
notify:
  enabled: true
  image:
    repository: movingtowardsadream/notify:1.0
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  resources: {}
    # limits:
    #   cpu: "500m"
    #   memory: "512Mi"
    # requests:
    #   cpu: "250m"
  #   memory: "256Mi"

# Общие настройки
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
