name: Migrate for Notification Service

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deployment'
        required: true

jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DEPLOY_DIRECTORY: /root/apps/notify-service
      CONFIG_PATH: /root/apps/notify-service/configs/testing.yaml
      ENV_PATH: /root/apps/notify-service/.env
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run migrations
        run: |
          go mod download
          go run ./cmd/migrate/main.go